language: php

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

  include:
    - php: nightly

    - php: 7.2
      env: PREFER_LOWEST=1

    - php: 7.3
      env: CODECOVERAGE=1

before_install:
  - |
      if [[ $CODECOVERAGE == 1 ]]; then
        pecl channel-update pecl.php.net
        pecl install pcov
      fi
  - phpenv config-rm xdebug.ini

install:
  - |
      if [[ $CODECOVERAGE == 1 ]]; then
        composer install --prefer-dist --no-interaction
      elif [[ $TRAVIS_PHP_VERSION == 'nightly' ]]; then
        composer install --no-interaction --ignore-platform-reqs
      else
        composer update --prefer-lowest --prefer-stable --no-interaction
      fi

script:
  - |
      if [[ $CODECOVERAGE == 1 ]]; then
        vendor/bin/phpunit --verbose --coverage-clover=clover.xml
      else
        vendor/bin/phpunit --verbose
      fi

after_success:
  - |
      if [[ $CODECOVERAGE == 1 ]]; then
        wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
        chmod +x php-coveralls.phar
        ./php-coveralls.phar
      fi

